data:
  cub_root: "/Users/sa/Documents/SCU/MLProject/data/CUB_200_2011"
  train_split: "splits/train.txt"
  val_split:   "splits/val.txt"
  test_split:  "splits/test.txt"

eval:
  batch_size: 64
  num_workers: 4

model:
  clip_model_name: "openai/clip-vit-base-patch16"
  # (optional) local_clip_path: "/Users/sa/Documents/SCU/MLProject/CLIP/clip"

train:
  lr: 1e-4
  epochs: 1

index:
  faiss_nlist: 100
  top_k: [1, 5, 10]
